Added upgrade&restart script

diff --git a/bin/csctrl b/bin/csctrl
--- a/bin/csctrl
+++ b/bin/csctrl
@@ -2,6 +2,7 @@
 
 CSOWNER=%CSGO_USERNAME%
 CSGODIR=/home/${CSOWNER}/csgosv
+RCODE=0
 
 start() {
     /home/${CSOWNER}/bin/csgenmapchange   # generate the mapchange.cfg with convenience aliases
@@ -11,15 +12,28 @@ start() {
 
 stop() {
     steamcmd +login anonymous +force_install_dir ${CSGODIR}  +app_stop 740 +quit
+    RCODE=$?
     killer -f
 }
 
 killer() {
-   if [ "x$1" = "x-f" ];
+   if [ "x$1" == "x-f" ];
      then killall -9 srcds_linux srcds_run
      else kill -9 $(cat ${CSGODIR}/csgosv.pid) # but will restart
   fi
 }
+
+
+upgrade() { # autoupdate & restarts script, needs to be run as root -> root's crontab
+   update -f
+   if [ RCODE == 0];
+     then echo sudo shutdown -r now
+      echo "`date`  CS updated, restarting instance..." >> /home/ubuntu/updatelog.txt
+     else echo "`date`  error during CS update, not restarted. Code: ${RCODE}" >> /home/ubuntu/updatelog.txt
+   fi
+}
+
+
 
 case "$1" in
     start)
@@ -39,10 +53,15 @@ case "$1" in
        steamcmd +login anonymous +force_install_dir ${CSGODIR} +app_status 740 +quit
        ;;
     update)
-       if [ "x$2" = "x-f" ];
+       if [ "x$2" == "x-f" ];
          then steamcmd +login anonymous +force_install_dir ${CSGODIR} +app_update 740 validate +quit
+           RCODE=$?
          else steamcmd +login anonymous +force_install_dir ${CSGODIR} +app_update 740 +quit
+           RCODE=$?
       fi
+       ;;
+    upgrade)
+       upgrade
        ;;
     *)
        echo "Usage: $0 {start|stop|restart|status|update}"
